# Generated by Django 4.2 on 2024-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='create_date',
            field=models.DateField(verbose_name='дата выхода продукта на рынок'),
        ),
    ]
